### ISSUE TITLE
PowerShell code cleanup

### ISSUE THREAD

**Issue by bjompen** [kevchant/AzureDevOps-dedicatedSQLPoolToFabricDW#2]
The only big thing I noticed
- match and notmatch are RegEx comparisons and as such the "exclude lines starting with 'WITH'" part may have unexpected issues. Replacing the RegEx with '^\s*WITH' should solve this. If you want it to be _only_ capital WITH, and not match lower case with, you may use the -cnotmatch operator as well.
![image](https://github.com/kevchant/AzureDevOps-dedicatedSQLPoolToFabricDW/assets/17783007/d0919cbf-2877-4717-9688-52cbf2e7a5d2)

Minor things:
- Using Select on line 66 only limits the properties sent on through the pipeline. We can clean up the code by using `Select-Object -ExpandProperty` and have a string array right away instead
![image](https://github.com/kevchant/AzureDevOps-dedicatedSQLPoolToFabricDW/assets/17783007/0f7d5fa2-4f08-45f2-b22b-5521b2c2f2bf)
- Twice you're doing `cd.. ; cd a`. One of them, in the `dotnet  new sqlproj` task, doesn't seem to do anything and can be removed, The other one could be [replaced by](https://learn.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#build-variables-devops-services) `Set-Location $(Build.ArtifactStagingDirectory)`? Otherwise a change of working directory may mess up the workflow.

**Comment by kevchant** [comment]
Tested proposed changes and all looks well.  Thanks.
